var Modal=function(){var e=document.querySelectorAll(".modal__trigger"),p=document.querySelectorAll(".modal"),q=document.querySelectorAll(".modal__bg"),r=document.querySelectorAll(".modal__content"),t=document.querySelectorAll(".modal__close"),l=window,f=!1,m=e.length,v=function(a){a.preventDefault();a=this.dataset.modal;a=a.substring(1,a.length);a=document.getElementById(a);if(null===document.getElementById("modal__temp")){var c=document.createElement("div");c.id="modal__temp";this.appendChild(c);
u(this,a,c)}},u=function(a,c,d){var b=a.getBoundingClientRect(),e=c.querySelector(".modal__content").getBoundingClientRect();var f=l.innerWidth/2;var g=l.innerHeight/2;a.classList.add("modal__trigger--active");var h=e.width/b.width;var k=e.height/b.height;h=h.toFixed(3);k=k.toFixed(3);f=Math.round(f-b.left-b.width/2);g=Math.round(g-b.top-b.height/2);c.classList.contains("modal--align-top")&&(g=Math.round(e.height/2+e.top-b.top-b.height/2));a.style.transform="translate("+f+"px, "+g+"px)";a.style.webkitTransform=
"translate("+f+"px, "+g+"px)";d.style.transform="scale("+h+","+k+")";d.style.webkitTransform="scale("+h+","+k+")";window.setTimeout(function(){window.requestAnimationFrame(function(){w(c,d)})},400)},w=function(a,c){function d(){c.style.opacity="0";b.removeEventListener("transitionend",d,!1)}if(!f){var b=a.querySelector(".modal__content");a.classList.add("modal--active");b.classList.add("modal__content--active");b.addEventListener("transitionend",d,!1);f=!0}},n=function(a){function c(){setTimeout(function(){window.requestAnimationFrame(function(){d.remove()})},
350)}a.preventDefault();a.stopImmediatePropagation();a=a.target;var d=document.getElementById("modal__temp");if(f&&a.classList.contains("modal__bg")||a.classList.contains("modal__close")){d.style.opacity="1";d.removeAttribute("style");for(a=0;a<m;a++)p[a].classList.remove("modal--active"),r[a].classList.remove("modal__content--active"),e[a].style.transform="none",e[a].style.webkitTransform="none",e[a].classList.remove("modal__trigger--active");d.addEventListener("transitionend",c,!1);f=!1}};return{init:function(){for(var a=
0;a<m;a++)e[a].addEventListener("click",v,!1),t[a].addEventListener("click",n,!1),q[a].addEventListener("click",n,!1)}}}();Modal.init();

function s(i){
  fbRef.child('Players/' + pid).remove();
  document.cookie="color="+i;
  window.location=window.location
}
